name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - scikit-learn=0.24.1
  - matplotlib==3.2.2
  - plotly==4.4.1
  - pillow=8.1.2
  - pip:
      - wandb==0.10.21